spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    platform: postgres
    initialization-mode: always
    initialize: true


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

app:
  bank:
    externalBankEntitiesConfig:
      -
        id: 4120
        name: "SABADELL"
        atmOperationComission: 8.0
        outgoingTransferComission: 1.0
      -
        id: 1320
        name: "CAJAMAR"
        atmOperationComission: 13.0
        outgoingTransferComission: 3.0
      -
        id: 1110
        name: "CAIXABANK"
        atmOperationComission: 15.0
        outgoingTransferComission: 2.0